'use strict';
module.exports = (sequelize, DataTypes) => {
  const Project = sequelize.define('Project', {
    项目ID: DataTypes.STRING,
    项目名称: DataTypes.STRING,
    城市: DataTypes.STRING,
    总建筑面积: DataTypes.STRING,
    定位: DataTypes.STRING,
    交通条件: DataTypes.STRING,
    业主结构: DataTypes.STRING,
    区域: DataTypes.STRING,
    细分定位: DataTypes.INTEGER,
    地上建筑面积: DataTypes.STRING,
    地下建筑面积: DataTypes.STRING,
    停车场建筑面积: DataTypes.STRING,
    总可租赁面积: DataTypes.STRING,
    租户数量: DataTypes.STRING,
    停车场数量: DataTypes.STRING,
    平均租金: DataTypes.STRING,
    平均物管费: DataTypes.STRING,
    餐饮平均租金: DataTypes.STRING,
    服装平均租金: DataTypes.STRING,
    超市平均租金: DataTypes.STRING,
    餐饮平均租金增长率: DataTypes.INTEGER,
    服装平均租金增长率: DataTypes.STRING,
    超市平均租金增长率: DataTypes.STRING,
    停车场租金: DataTypes.STRING,
    多经收入: DataTypes.STRING,
    广告位收入: DataTypes.STRING,
    仓库收入: DataTypes.STRING,
    多经点位收入: DataTypes.STRING,
    场地租赁收入: DataTypes.STRING,
    运营支出: DataTypes.STRING,
    非运营支出: DataTypes.STRING,
    保安费用: DataTypes.INTEGER,
    保洁费用: DataTypes.STRING,
    人力行政费用: DataTypes.STRING,
    推广费用: DataTypes.STRING,
    能耗费用: DataTypes.STRING,
    工程维保费用: DataTypes.INTEGER,
    保险及其他费用: DataTypes.STRING,
    保安人员数量: DataTypes.STRING,
    保洁人员数量: DataTypes.STRING,
    保安人员工资标准: DataTypes.STRING,
    保洁人员工资标准: DataTypes.STRING,
    行政人员数量: DataTypes.STRING,
    招商人员数量: DataTypes.STRING,
    推广人员数量: DataTypes.STRING,
    工程人员数量: DataTypes.STRING,
    水费: DataTypes.STRING,
    电费: DataTypes.INTEGER,
    总收购成本: DataTypes.STRING,
    开发成本: DataTypes.STRING,
    土地成本: DataTypes.STRING,
    拆迁补偿: DataTypes.STRING,
    市政费: DataTypes.INTEGER,
    前期准备费用: DataTypes.STRING,
    建安成本: DataTypes.STRING,
    公共事业费: DataTypes.STRING,
    开发间接管理费: DataTypes.STRING,
    开业准备费用: DataTypes.STRING,
    不可预见费: DataTypes.STRING,
    开发管理费: DataTypes.STRING,
    其他管理费: DataTypes.STRING,
    月均客流量: DataTypes.STRING,
    月均销售额: DataTypes.STRING,
    开业率: DataTypes.INTEGER,
    客单价: DataTypes.STRING,
    交易对手: DataTypes.STRING,
    交易价格: DataTypes.STRING,
    交易方式: DataTypes.STRING,
    资本化率: DataTypes.STRING,
    交易时间: DataTypes.STRING
  }, {});
  Project.associate = function(models) {
    // associations can be defined here
  };
  return Project;
};


																	
